# Generated by Django 3.1.4 on 2020-12-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project/', verbose_name='프로젝트 이미지')),
                ('title', models.CharField(max_length=20, verbose_name='프로젝트 제목')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
            ],
        ),
    ]
