# Generated by Django 3.1.4 on 2020-12-23 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articleapp', '0002_auto_20201223_1437'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=511, verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='articleapp.article', verbose_name='게시물')),
                ('writer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
