# Generated by Django 3.1.4 on 2020-12-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=511, verbose_name='댓글 내용'),
        ),
    ]
