# Generated by Django 3.1.4 on 2020-12-23 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='작성 날짜')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='제목')),
                ('image', models.ImageField(upload_to='article/%Y/%m/%d', verbose_name='이미지')),
                ('content', models.TextField(null=True, verbose_name='본문')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_set', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
